// ui/app/page.tsx
"use client"

import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { GlowingEffect } from "@/components/ui/glowing-effect"
import { CircleArrowRight, ArrowRight } from "lucide-react"
import { useEffect, useState } from "react"
import { Navbar } from "@/components/navbar"
import Script from "next/script"

export default function Home() {
  const [scrollProgress, setScrollProgress] = useState(0)

  useEffect(() => {
    const handleScroll = () => {
      const scrollY = window.scrollY
      const viewportHeight = window.innerHeight
      // Calculate progress from 0 to 1 over one viewport height
      const progress = Math.min(scrollY / viewportHeight, 1)
      setScrollProgress(progress)
    }

    window.addEventListener("scroll", handleScroll)
    return () => window.removeEventListener("scroll", handleScroll)
  }, [])

  // Calculate opacity and scale based on scroll
  const linesOpacity = 1 - scrollProgress
  const linesScale = 1 - scrollProgress * 0.3 // Scale from 1 to 0.7

  const scrollToCapabilities = () => {
    const capabilitiesSection = document.getElementById("capabilities")
    if (capabilitiesSection) {
      capabilitiesSection.scrollIntoView({ behavior: "smooth" })
    }
  }

  return (
    <main className="relative min-h-[200vh] bg-black text-white overflow-hidden">
      <Script
        src="https://unpkg.com/@splinetool/viewer@1.0.17/build/spline-viewer.js"
        type="module"
        strategy="afterInteractive"
      />

      <Navbar />

      <div
        className="fixed inset-0 z-0 w-screen h-screen pointer-events-none transition-all duration-100"
        style={{
          opacity: linesOpacity,
          transform: `scale(${linesScale})`,
        }}
      >
        <div className="bg-lines-container">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="2269"
            height="2108"
            viewBox="0 0 2269 2108"
            fill="none"
            className="w-full h-full"
            preserveAspectRatio="xMidYMid slice"
          >
            {/* Animated Purple Lines */}
            <path
              d="M510.086 0.543457L507.556 840.047C506.058 1337.18 318.091 1803.4 1.875 2094.29"
              stroke="#4C00EC"
              strokeWidth="2"
              strokeMiterlimit="10"
              strokeDasharray="100px 99999px"
              className="animate-line-race-1"
            />
            <path
              d="M929.828 0.543457L927.328 829.877C925.809 1334 737.028 1807.4 418.435 2106"
              stroke="#4C00EC"
              strokeWidth="2"
              strokeMiterlimit="10"
              strokeDasharray="100px 99999px"
              className="animate-line-race-2"
            />
            <path
              d="M1341.9 0.543457L1344.4 829.876C1345.92 1334 1534.7 1807.4 1853.29 2106"
              stroke="#4C00EC"
              strokeWidth="2"
              strokeMiterlimit="10"
              strokeDasharray="100px 99999px"
              className="animate-line-race-3"
            />
            <path
              d="M1758.96 0.543457L1761.49 840.047C1762.99 1337.18 1950.96 1803.4 2267.17 2094.29"
              stroke="#4C00EC"
              strokeWidth="2"
              strokeMiterlimit="10"
              strokeDasharray="100px 99999px"
              className="animate-line-race-4"
            />

            {/* Static White Background Lines */}
            <path
              opacity="0.2"
              d="M929.828 0.543457L927.328 829.877C925.809 1334 737.028 1807.4 418.435 2106"
              stroke="white"
              strokeWidth="1"
              strokeMiterlimit="10"
            />
            <path
              opacity="0.2"
              d="M510.086 0.543457L507.556 840.047C506.058 1337.18 318.091 1803.4 1.875 2094.29"
              stroke="white"
              strokeWidth="1"
              strokeMiterlimit="10"
            />
            <path
              opacity="0.2"
              d="M1758.96 0.543457L1761.49 840.047C1762.99 1337.18 1950.96 1803.4 2267.17 2094.29"
              stroke="white"
              strokeWidth="1"
              strokeMiterlimit="10"
            />
            <path
              opacity="0.2"
              d="M1341.9 0.543457L1344.4 829.876C1345.92 1334 1534.7 1807.4 1853.29 2106"
              stroke="white"
              strokeWidth="1"
              strokeMiterlimit="10"
            />
          </svg>
        </div>
      </div>

      {/* 3D Spline Viewer */}
      <div
        className="fixed right-0 top-0 w-1/2 h-screen pointer-events-none z-10"
        style={{
          opacity: linesOpacity,
          transform: `scale(${linesScale})`,
        }}
      >
        <div className="track">
          <spline-viewer
            url="https://prod.spline.design/ZxKIijKh056svcM5/scene.splinecode"
            className="w-full h-full"
            style={{ position: "sticky", top: "0px", height: "100vh" }}
          />
        </div>
      </div>

      {/* Hero Content */}
      <div id="hero" className="relative z-20 container mx-auto px-6 lg:px-12 pt-24 pb-32 min-h-screen flex flex-col justify-center">
        <div className="max-w-3xl">
          {/* Status / Tagline */}
          <div className="flex items-center gap-3 mb-12 animate-fade-in">
            <div className="relative w-14 h-7 bg-gradient-to-r from-green-400 to-green-500 rounded-full">
              <div className="absolute right-1 top-1 w-5 h-5 bg-white rounded-full transition-transform duration-300" />
            </div>
            <span className="text-sm text-zinc-300">The agentic kit for Stellar DeFi.</span>
          </div>

          {/* Main Heading */}
          <h1 className="text-6xl md:text-7xl lg:text-8xl font-light mb-8 leading-[1] animate-fade-in-up text-balance">
            Warly
          </h1>

          {/* Subheading */}
          <p className="text-lg md:text-xl text-zinc-400 mb-12 animate-fade-in-up animation-delay-200">
            Stellar DeFi in plain language. Check balances, swap XLM ↔ USDC, create trustlines, and get quotes—all through an AI agent.
          </p>

          {/* CTA Button */}
          <div className="animate-fade-in-up animation-delay-400">
            <Button
              size="lg"
              onClick={scrollToCapabilities}
              className="group bg-[#5100fd] hover:bg-[#6610ff] text-white px-8 py-6 text-base rounded-full transition-all duration-[650ms] hover:scale-[1.02]"
            >
              Explore Capabilities
              <CircleArrowRight className="ml-2 h-5 w-5 transition-transform duration-[650ms] group-hover:rotate-90" />
            </Button>
          </div>
        </div>
      </div>

      {/* Capabilities section with tabs */}
      <section id="capabilities" className="relative z-20 py-24">
        <div className="container p-12 rounded-2xl z-50 bg-(#09090b) border border-zinc-800 mx-auto px-6 lg:px-12">
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-light mb-6 text-balance">Capabilities</h2>

          <p className="text-lg md:text-xl text-zinc-400 mb-12">
            One CLI. One agent. Four tools powered by Stellar and SoroSwap.
          </p>

          <Tabs defaultValue="tools" className="w-full">
            <TabsList className="bg-zinc-950 border border-zinc-800 p-1 mb-8 rounded-full">
              <TabsTrigger
                value="tools"
                className="text-zinc-500 data-[state=active]:bg-[#5100fd] data-[state=active]:text-white px-8 py-3 rounded-full transition-all"
              >
                Agent tools
              </TabsTrigger>
              <TabsTrigger
                value="flow"
                className="text-zinc-500 data-[state=active]:bg-[#5100fd] data-[state=active]:text-white px-8 py-3 rounded-full transition-all"
              >
                How it works
              </TabsTrigger>
            </TabsList>

            <TabsContent value="tools" className="mt-8">
              <div className="grid md:grid-cols-2 gap-8">
                <div className="relative rounded-2xl border border-zinc-800 p-3">
                  <GlowingEffect
                    blur={0}
                    borderWidth={2}
                    spread={80}
                    glow={true}
                    disabled={false}
                    proximity={64}
                    inactiveZone={0.01}
                  />
                  <div className="relative bg-(#0a0a0a) rounded-xl p-8">
                    <h3 className="text-2xl font-light mb-4">Check balance</h3>
                    <p className="text-zinc-400 leading-relaxed mb-6">
                      Get token balances for any Stellar address on mainnet or testnet via Horizon.
                    </p>
                    <a
                      href="https://github.com/stellar/stellar-agent-kit"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center text-white hover:text-zinc-300 transition-colors duration-300 group"
                    >
                      <span className="underline">Get started</span>
                      <ArrowRight className="ml-1 h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
                    </a>
                  </div>
                </div>
                <div className="relative rounded-2xl border border-zinc-800 p-3">
                  <GlowingEffect
                    blur={0}
                    borderWidth={2}
                    spread={80}
                    glow={true}
                    disabled={false}
                    proximity={64}
                    inactiveZone={0.01}
                  />
                  <div className="relative bg-(#0a0a0a) rounded-xl p-8">
                    <h3 className="text-2xl font-light mb-4">Swap assets</h3>
                    <p className="text-zinc-400 leading-relaxed mb-6">
                      Swap XLM ↔ USDC via SoroSwap. Quote first, then execute with your key. Mainnet-ready.
                    </p>
                    <a
                      href="https://github.com/stellar/stellar-agent-kit"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center text-white hover:text-zinc-300 transition-colors duration-300 group"
                    >
                      <span className="underline">Get started</span>
                      <ArrowRight className="ml-1 h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
                    </a>
                  </div>
                </div>
                <div className="relative rounded-2xl border border-zinc-800 p-3">
                  <GlowingEffect
                    blur={0}
                    borderWidth={2}
                    spread={80}
                    glow={true}
                    disabled={false}
                    proximity={64}
                    inactiveZone={0.01}
                  />
                  <div className="relative bg-(#0a0a0a) rounded-xl p-8">
                    <h3 className="text-2xl font-light mb-4">Create trustline</h3>
                    <p className="text-zinc-400 leading-relaxed mb-6">
                      Create a USDC trustline so your account can receive and hold USDC on mainnet or testnet.
                    </p>
                    <a
                      href="https://github.com/stellar/stellar-agent-kit"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center text-white hover:text-zinc-300 transition-colors duration-300 group"
                    >
                      <span className="underline">Get started</span>
                      <ArrowRight className="ml-1 h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
                    </a>
                  </div>
                </div>
                <div className="relative rounded-2xl border border-zinc-800 p-3">
                  <GlowingEffect
                    blur={0}
                    borderWidth={2}
                    spread={80}
                    glow={true}
                    disabled={false}
                    proximity={64}
                    inactiveZone={0.01}
                  />
                  <div className="relative bg-(#0a0a0a) rounded-xl p-8">
                    <h3 className="text-2xl font-light mb-4">Get swap quote</h3>
                    <p className="text-zinc-400 leading-relaxed mb-6">
                      Get a quote only—no execution, no private key. Perfect for checking rates before you swap.
                    </p>
                    <a
                      href="https://github.com/stellar/stellar-agent-kit"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center text-white hover:text-zinc-300 transition-colors duration-300 group"
                    >
                      <span className="underline">Get started</span>
                      <ArrowRight className="ml-1 h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
                    </a>
                  </div>
                </div>
              </div>
            </TabsContent>

            <TabsContent value="flow" className="mt-8">
              <div className="grid md:grid-cols-2 gap-8">
                <div className="relative rounded-2xl border border-zinc-800 p-3">
                  <GlowingEffect
                    blur={0}
                    borderWidth={2}
                    spread={80}
                    glow={true}
                    disabled={false}
                    proximity={64}
                    inactiveZone={0.01}
                  />
                  <div className="relative bg-(#0a0a0a) rounded-xl p-8">
                    <h3 className="text-2xl font-light mb-4">You ask</h3>
                    <p className="text-zinc-400 leading-relaxed mb-6">
                      Talk in plain language. e.g. &ldquo;Swap 0.2 XLM to USDC&rdquo; or &ldquo;Check my balance.&rdquo;
                    </p>
                    <a
                      href="https://github.com/stellar/stellar-agent-kit"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center text-white hover:text-zinc-300 transition-colors duration-300 group"
                    >
                      <span className="underline">Get started</span>
                      <ArrowRight className="ml-1 h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
                    </a>
                  </div>
                </div>
                <div className="relative rounded-2xl border border-zinc-800 p-3">
                  <GlowingEffect
                    blur={0}
                    borderWidth={2}
                    spread={80}
                    glow={true}
                    disabled={false}
                    proximity={64}
                    inactiveZone={0.01}
                  />
                  <div className="relative bg-(#0a0a0a) rounded-xl p-8">
                    <h3 className="text-2xl font-light mb-4">Agent chooses tool</h3>
                    <p className="text-zinc-400 leading-relaxed mb-6">
                      The LLM picks the right tool (check_balance, swap_asset, create_trustline, get_swap_quote) and parameters.
                    </p>
                    <a
                      href="https://github.com/stellar/stellar-agent-kit"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center text-white hover:text-zinc-300 transition-colors duration-300 group"
                    >
                      <span className="underline">Get started</span>
                      <ArrowRight className="ml-1 h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
                    </a>
                  </div>
                </div>
                <div className="relative rounded-2xl border border-zinc-800 p-3">
                  <GlowingEffect
                    blur={0}
                    borderWidth={2}
                    spread={80}
                    glow={true}
                    disabled={false}
                    proximity={64}
                    inactiveZone={0.01}
                  />
                  <div className="relative bg-(#0a0a0a) rounded-xl p-8">
                    <h3 className="text-2xl font-light mb-4">Tool runs</h3>
                    <p className="text-zinc-400 leading-relaxed mb-6">
                      Quote → build → sign → submit. Stellar + SoroSwap + Soroban RPC. You get txHash or quote back.
                    </p>
                    <a
                      href="https://github.com/stellar/stellar-agent-kit"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center text-white hover:text-zinc-300 transition-colors duration-300 group"
                    >
                      <span className="underline">Get started</span>
                      <ArrowRight className="ml-1 h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
                    </a>
                  </div>
                </div>
                <div className="relative rounded-2xl border border-zinc-800 p-3">
                  <GlowingEffect
                    blur={0}
                    borderWidth={2}
                    spread={80}
                    glow={true}
                    disabled={false}
                    proximity={64}
                    inactiveZone={0.01}
                  />
                  <div className="relative bg-(#0a0a0a) rounded-xl p-8">
                    <h3 className="text-2xl font-light mb-4">You get the result</h3>
                    <p className="text-zinc-400 leading-relaxed mb-6">
                      Balances, swap txHash, trustline confirmation, or a human-readable quote—right in the chat.
                    </p>
                    <a
                      href="https://github.com/stellar/stellar-agent-kit"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center text-white hover:text-zinc-300 transition-colors duration-300 group"
                    >
                      <span className="underline">Get started</span>
                      <ArrowRight className="ml-1 h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
                    </a>
                  </div>
                </div>
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </section>
    </main>
  )
}

// landing/src/App.vue
<template>
  <div class="warly-landing">
    <!-- Navbar -->
    <fish-layout class="navbar">
      <div slot="header" class="nav-header">
        <div class="nav-inner">
          <span class="logo">Warly</span>
          <fish-menu mode="horizontal" class="nav-menu" @change="onMenuChange">
            <fish-option index="1" content="Home"></fish-option>
            <fish-option index="2" content="Features"></fish-option>
            <fish-option index="3" content="Tools"></fish-option>
            <fish-option index="4" content="Get Started"></fish-option>
          </fish-menu>
        </div>
      </div>
      <div slot="content" style="display:none;"></div>
    </fish-layout>

    <!-- Hero -->
    <section id="hero" class="hero">
      <div class="hero-content">
          <fish-tag class="hero-tag" type="primary">The Agentic Kit</fish-tag>
          <h1 class="hero-title">Warly</h1>
          <p class="hero-subtitle">
            Stellar DeFi in plain language. Check balances, swap XLM ↔ USDC, create trustlines, and get quotes—all through an AI agent.
          </p>
          <div class="hero-actions">
            <fish-button type="primary" size="large" @click="scrollTo('tools')">
              <i class="fa fa-bolt"></i> See tools
            </fish-button>
            <fish-button size="large" @click="scrollTo('features')">
              <i class="fa fa-book"></i> How it works
            </fish-button>
          </div>
        </div>
    </section>

    <!-- Features -->
    <section id="features" class="features">
      <div class="section-inner">
        <h2 class="section-title">How it works</h2>
        <p class="section-desc">One CLI. One agent. Four tools powered by Stellar and SoroSwap.</p>
        <fish-row :gutter="24" class="feature-cards">
          <fish-col :span="12">
            <fish-card class="feature-card">
              <div class="card-icon"><i class="fa fa-wallet"></i></div>
              <h3>Check balance</h3>
              <p>Get token balances for any Stellar address on mainnet or testnet.</p>
            </fish-card>
          </fish-col>
          <fish-col :span="12">
            <fish-card class="feature-card">
              <div class="card-icon"><i class="fa fa-exchange"></i></div>
              <h3>Swap assets</h3>
              <p>Swap XLM ↔ USDC via SoroSwap. Quote first, then execute with your key.</p>
            </fish-card>
          </fish-col>
          <fish-col :span="12">
            <fish-card class="feature-card">
              <div class="card-icon"><i class="fa fa-link"></i></div>
              <h3>Create trustline</h3>
              <p>Create a USDC trustline so your account can receive and hold USDC.</p>
            </fish-card>
          </fish-col>
          <fish-col :span="12">
            <fish-card class="feature-card">
              <div class="card-icon"><i class="fa fa-calculator"></i></div>
              <h3>Get swap quote</h3>
              <p>Get a quote only—no execution, no private key. Perfect for checking rates.</p>
            </fish-card>
          </fish-col>
        </fish-row>
      </div>
    </section>

    <!-- Tools / Flow -->
    <section id="tools" class="tools">
      <div class="section-inner">
        <h2 class="section-title">Agent flow</h2>
        <p class="section-desc">You chat. The LLM picks the right tool and runs it.</p>
        <fish-steps class="flow-steps">
          <fish-step title="You ask" description="e.g. Swap 0.2 XLM to USDC" />
          <fish-step title="Agent chooses tool" description="swap_asset with params" active />
          <fish-step title="Tool runs" description="Quote → build → sign → submit" />
          <fish-step title="You get result" description="txHash + status or quote" />
        </fish-steps>
      </div>
    </section>

    <!-- CTA -->
    <section id="cta" class="cta">
      <div class="section-inner cta-inner">
        <h2 class="section-title">Ready to try Warly?</h2>
        <p class="section-desc">Clone the repo, set your keys, and run the agent.</p>
        <fish-button type="primary" size="large" @click="openRepo">
          <i class="fa fa-github"></i> View on GitHub
        </fish-button>
      </div>
    </section>

    <!-- Footer -->
    <footer class="footer">
      <div class="footer-inner">
        <span>Warly: the agentic kit</span>
        <span>Stellar DeFi + LLM agent</span>
      </div>
    </footer>
  </div>
</template>

<script>
export default {
  name: 'WarlyLanding',
  methods: {
    scrollTo (id) {
      const el = document.getElementById(id)
      if (el) el.scrollIntoView({ behavior: 'smooth' })
    },
    onMenuChange (index) {
      const ids = { '1': 'hero', '2': 'features', '3': 'tools', '4': 'cta' }
      if (ids[index]) this.scrollTo(ids[index])
    },
    openRepo () {
      window.open('https://github.com/stellar/stellar-agent-kit', '_blank')
    },
  },
}
</script>

<style lang="less" scoped>
.warly-landing {
  font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
  background: #0a0a0f;
  color: #e4e4e7;
  min-height: 100vh;
}

.navbar {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 100;
}
.nav-header {
  background: rgba(10, 10, 15, 0.9);
  border-bottom: 1px solid #27272a;
  padding: 0 24px;
  height: 64px;
  line-height: 64px;
}
.nav-inner {
  max-width: 1200px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.logo {
  font-size: 1.5rem;
  font-weight: 700;
  color: #a78bfa;
}
.nav-menu {
  background: transparent !important;
  border: none !important;
}

.hero {
  padding: 120px 24px 80px;
  text-align: center;
}
.hero-layout {
  background: transparent;
}
.hero-content {
  max-width: 640px;
  margin: 0 auto;
}
.hero-tag {
  display: inline-block;
  margin-bottom: 16px;
  padding: 6px 12px;
  border-radius: 6px;
  font-size: 0.875rem;
}
.hero-title {
  font-size: 3.5rem;
  font-weight: 700;
  margin: 0 0 16px;
  color: #fff;
  letter-spacing: -0.02em;
}
.hero-subtitle {
  font-size: 1.25rem;
  color: #a1a1aa;
  line-height: 1.6;
  margin: 0 0 32px;
}
.hero-actions {
  display: flex;
  gap: 16px;
  justify-content: center;
  flex-wrap: wrap;
}

.section-inner {
  max-width: 1000px;
  margin: 0 auto;
  padding: 64px 24px;
}
.section-title {
  font-size: 2rem;
  font-weight: 600;
  margin: 0 0 8px;
  color: #fff;
  text-align: center;
}
.section-desc {
  font-size: 1.125rem;
  color: #a1a1aa;
  text-align: center;
  margin: 0 0 40px;
}

.features {
  background: #09090b;
  border-top: 1px solid #27272a;
}
.feature-cards {
  margin-top: 24px;
}
.feature-card {
  background: #18181b !important;
  border: 1px solid #27272a !important;
  margin-bottom: 24px;
  padding: 24px !important;
  color: #e4e4e7;
}
.feature-card h3 {
  margin: 0 0 8px;
  font-size: 1.25rem;
  color: #fff;
}
.feature-card p {
  margin: 0;
  color: #a1a1aa;
  font-size: 0.9375rem;
  line-height: 1.5;
}
.card-icon {
  width: 48px;
  height: 48px;
  border-radius: 12px;
  background: rgba(167, 139, 250, 0.2);
  color: #a78bfa;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 1.5rem;
  margin-bottom: 16px;
}

.tools {
  padding-bottom: 48px;
}
.flow-steps {
  max-width: 640px;
  margin: 0 auto;
}
.flow-steps /deep/ .fish-steps-item {
  color: #a1a1aa;
}
.flow-steps /deep/ .fish-steps-item.fish-steps-item-finish,
.flow-steps /deep/ .fish-steps-item.fish-steps-item-process {
  color: #a78bfa;
}

.cta {
  background: #18181b;
  border-top: 1px solid #27272a;
}
.cta-inner {
  padding: 64px 24px;
}

.footer {
  background: #09090b;
  border-top: 1px solid #27272a;
  color: #71717a;
  text-align: center;
  padding: 24px;
}
.footer-inner {
  display: flex;
  justify-content: center;
  gap: 24px;
  flex-wrap: wrap;
}
</style>
